const questionBank = [
  {id:1,type:'mc',difficulty:'easy',slideRef:'Section 1.4 — Key Array/List Operations and Big-O',question:'What is the time complexity of accessing an element by index (arr[i]) in a Python list?',correctAnswer:'O(1)',origChoices:['O(n)','O(log n)','O(1)','O(n^2)'],origWhy:['O(n) is linear time — used for searching an unsorted list, not for index access.','O(log n) is logarithmic — used for binary search on sorted data, not direct index access.','O(1) is correct. Direct index access in a Python list is constant-time because the list knows exactly where each element is stored.','O(n^2) is quadratic — typical of nested loops like Bubble Sort, not index access.'],choices:[],why:[],altAnswers:[]},
  {id:2,type:'mc',difficulty:'easy',slideRef:'Section 1.3 — Python Lists vs. Tuples vs. Dictionaries',question:'Which Python data structure is immutable (cannot be changed after creation)?',correctAnswer:'Tuple',origChoices:['List','Tuple','Dictionary','Array (list)'],origWhy:['A List is mutable — it supports adding, removing, and changing elements.','A Tuple is correct. It is an immutable sequence used for fixed data that should not change.','A Dictionary is mutable (and ordered since Python 3.7). Keys and values can be added or modified.','Python lists (used as the array equivalent) are mutable and dynamic.'],choices:[],why:[],altAnswers:[]},
  {id:3,type:'mc',difficulty:'easy',slideRef:'Section 1.4 — Key Array/List Operations and Big-O',question:'What is the time complexity of arr.insert(i, x) — inserting an element at a specific position in a Python list?',correctAnswer:'O(n)',origChoices:['O(1)','O(log n)','O(n)','O(n log n)'],origWhy:['O(1) is constant time — achieved by arr.append(x), not by inserting at an arbitrary position.','O(log n) is logarithmic — used in binary search, not list insertions.','O(n) is correct. Inserting at position i requires shifting all subsequent elements, which takes linear time.','O(n log n) is the complexity of sorting (arr.sort()), not insertion.'],choices:[],why:[],altAnswers:[]},
  {id:4,type:'mc',difficulty:'easy',slideRef:'Section 1.2 — 1D vs. 2D Arrays',question:'Given grid = [[1,2,3],[4,5,6],[7,8,9]], what does grid[1][2] return?',correctAnswer:'6',origChoices:['5','7','4','6'],origWhy:['5 would be grid[1][1] — row 1, column 1.','7 would be grid[2][0] — row 2, column 0.','4 would be grid[1][0] — row 1, column 0.','6 is correct. grid[1][2] accesses row index 1 (which is [4,5,6]) and column index 2, giving 6.'],choices:[],why:[],altAnswers:[]},
  {id:5,type:'mc',difficulty:'medium',slideRef:'Section 2.4 — Analysis of Algorithms',question:'Who is formally credited with pioneering the study of algorithm analysis?',correctAnswer:'Donald Knuth',origChoices:['Alan Turing','Edmund Landau','Paul Bachmann','Donald Knuth'],origWhy:['Alan Turing is renowned for foundational computer science theory (Turing machines, computability), but is not credited in the reviewer for algorithm analysis.','Edmund Landau co-created Big-O notation (Bachmann–Landau notation), not the formal study of algorithm analysis.','Paul Bachmann co-created Big-O notation, not the formal study of algorithm analysis.','Donald Knuth is correct. The reviewer explicitly states he is the pioneer in the formal study of algorithm analysis.'],choices:[],why:[],altAnswers:[]},
  {id:6,type:'mc',difficulty:'medium',slideRef:'Section 3.1 — Big-O Overview',question:'Who created Big-O notation (also known as Bachmann–Landau notation)?',correctAnswer:'Paul Bachmann and Edmund Landau',origChoices:['Donald Knuth and Alan Turing','Paul Bachmann and Edmund Landau','Donald Knuth and Edmund Landau','Alan Turing and Paul Bachmann'],origWhy:['Donald Knuth pioneered algorithm analysis; Alan Turing is known for Turing machines. Neither created Big-O.','Paul Bachmann and Edmund Landau is correct. The reviewer states Big-O is "also called Bachmann–Landau notation," crediting both.','Donald Knuth pioneered algorithm analysis but did not create Big-O notation.','Neither Alan Turing nor Paul Bachmann alone created it — it was Bachmann and Landau together.'],choices:[],why:[],altAnswers:[]},
  {id:7,type:'mc',difficulty:'easy',slideRef:'Section 3.2 — Big-O Classes (from fastest to slowest)',question:'Which Big-O complexity class does Bubble Sort belong to?',correctAnswer:'O(n^2)',origChoices:['O(n log n)','O(n)','O(n^2)','O(log n)'],origWhy:['O(n log n) belongs to Quicksort and Merge Sort, not Bubble Sort.','O(n) is linear — achieved by a single scan, not a comparison-based sort like Bubble Sort.','O(n^2) is correct. The reviewer lists Bubble Sort as an example of the quadratic class, which increases in proportion to n*n.','O(log n) is logarithmic — achieved by Binary Search on sorted data, not a sorting algorithm.'],choices:[],why:[],altAnswers:[]},
  {id:8,type:'mc',difficulty:'easy',slideRef:'Section 1.4 — Key Array/List Operations and Big-O',question:'What is the time complexity of arr.sort() in Python?',correctAnswer:'O(n log n)',origChoices:['O(n)','O(n^2)','O(n log n)','O(log n)'],origWhy:['O(n) is linear — achieved by a single pass through a list, not a sort.','O(n^2) is quadratic — characteristic of Bubble Sort, not Python\'s built-in Timsort.','O(n log n) is correct. The reviewer lists arr.sort() as O(n log n).','O(log n) is logarithmic — achieved by Binary Search, not sorting.'],choices:[],why:[],altAnswers:[]},
  {id:9,type:'mc',difficulty:'easy',slideRef:'Section 2.5 — Types of Analysis',question:'Which type of algorithm analysis considers the maximum number of steps for any input of size n?',correctAnswer:'Worst-case',origChoices:['Best-case','Average-case','Amortized','Worst-case'],origWhy:['Best-case measures the minimum number of steps for the most optimal input of size n.','Average-case measures the average steps over all possible inputs of size n.','Amortized measures the average cost over a sequence of operations, spread over time.','Worst-case is correct. The reviewer defines it as "Maximum number of steps for any input of size n."'],choices:[],why:[],altAnswers:[]},
  {id:10,type:'mc',difficulty:'medium',slideRef:'Section 3.1 — Big-O Overview / Section 4.2 — Key Vocabulary',question:'In algorithm analysis, Big-O notation describes which aspect of performance?',correctAnswer:'The asymptotic upper bound on the algorithm\'s growth rate',origChoices:['The exact number of operations the algorithm performs','The best-case number of operations for optimal input','The asymptotic upper bound on the algorithm\'s growth rate','The minimum memory usage of the algorithm'],origWhy:['Big-O drops constants and lower-order terms — it does not give an exact count of operations.','Big-O describes worst-case asymptotic behavior, not best-case.','Correct. The reviewer and cheat sheet both define Big-O as the "asymptotic upper bound on an algorithm\'s growth rate; worst-case measure."','Space complexity measures memory usage. Big-O generally refers to time complexity growth in this context.'],choices:[],why:[],altAnswers:[]},
  {id:11,type:'mc',difficulty:'easy',slideRef:'Section 3.2 — Big-O Classes (from fastest to slowest)',question:'What is the time complexity of Binary Search?',correctAnswer:'O(log n)',origChoices:['O(n)','O(n^2)','O(n log n)','O(log n)'],origWhy:['O(n) is Linear Search — it works on unsorted data by scanning each element.','O(n^2) is quadratic — typical of nested-loop algorithms like Bubble Sort.','O(n log n) is used by Quicksort and Merge Sort.','O(log n) is correct. Binary Search halves the problem space each iteration, giving logarithmic complexity.'],choices:[],why:[],altAnswers:[]},
  {id:12,type:'mc',difficulty:'medium',slideRef:'Section 2.1 — What is an Algorithm?',question:'According to the reviewer, what are the three components of an algorithm?',correctAnswer:'Inputs, Steps/Instructions, Outputs',origChoices:['Variables, Functions, Loops','Memory, Speed, Accuracy','Input, Processing, Storage','Inputs, Steps/Instructions, Outputs'],origWhy:['Variables, functions, and loops are programming constructs, not the three components defined in the reviewer.','Memory, speed, and accuracy relate to performance considerations, not the structural definition of an algorithm.','Input/Processing/Storage is a common computing model but is not how the reviewer defines algorithm components.','Correct. The reviewer explicitly lists: a. Inputs — data fed into the algorithm; b. Steps/Instructions — ordered operations; c. Outputs — the result produced.'],choices:[],why:[],altAnswers:[]},
  {id:13,type:'mc',difficulty:'easy',slideRef:'Section 4.1 — Python List Methods — Time Complexity',question:'What is the time complexity of lst.pop() — removing the last element of a Python list?',correctAnswer:'O(1)',origChoices:['O(n)','O(log n)','O(1)','O(n^2)'],origWhy:['O(n) is the complexity of lst.pop(i) when removing at a specific index i (not the last element).','O(log n) is logarithmic — used in Binary Search, not list removal.','O(1) is correct. Removing the last element requires no shifting, so it is constant time.','O(n^2) is quadratic — typical of Bubble Sort, not a simple list operation.'],choices:[],why:[],altAnswers:[]},
  {id:14,type:'mc',difficulty:'easy',slideRef:'Section 3.3 — Big-O Determination Rules',question:'When simplifying Big-O, what does O(2n) reduce to?',correctAnswer:'O(n)',origChoices:['O(n^2)','O(2)','O(n log n)','O(n)'],origWhy:['O(n^2) is quadratic — a completely different complexity class; constants do not square the complexity.','O(2) is not a valid simplification; constants inside Big-O are dropped, not kept as the result.','O(n log n) is a higher class than O(n); dropping a constant multiplier does not change the class.','O(n) is correct. The reviewer states: "Dropping constants — O(2n) simplifies to O(n); only the dominant growth term is kept."'],choices:[],why:[],altAnswers:[]},
  {id:15,type:'mc',difficulty:'hard',slideRef:'Section 3.1 — Big-O Overview',question:'The formal definition of f(n) = O(g(n)) states that f(n) is bounded by c*g(n) for all n >= n0. Which statement correctly completes this definition?',correctAnswer:'f(n) <= c*g(n) for all n >= n0, where c > 0',origChoices:['f(n) < g(n) for all n','f(n) = g(n) for all n >= n0','f(n) <= c*g(n) for all n >= n0, where c > 0','f(n) > c*g(n) for all n >= n0'],origWhy:['Strict inequality without a constant multiplier is too restrictive; Big-O uses <= with a constant c.','f(n) = g(n) describes exact equality, not an asymptotic upper bound.','Correct. The reviewer states: "f(n) = O(g(n)) means there exists a constant c > 0 and n0 such that f(n) <= c*g(n) for all n >= n0." Big-O is an upper bound.','f(n) > c*g(n) would describe a lower bound (Big-Omega), not Big-O.'],choices:[],why:[],altAnswers:[]},
  {id:16,type:'mc',difficulty:'medium',slideRef:'Section 3.2 — Big-O Classes (from fastest to slowest)',question:'What Big-O complexity class describes the Travelling Salesman Problem solved by brute force?',correctAnswer:'O(n!)',origChoices:['O(c^n)','O(n^2)','O(n!)','O(n log n)'],origWhy:['O(c^n) is Exponential — the reviewer associates this with the Travelling Salesman solved using dynamic programming, not brute force.','O(n^2) is Quadratic — typical of Bubble Sort, not the Travelling Salesman problem.','O(n!) is correct. The reviewer states brute-force Travelling Salesman is O(n!), increasing as the product of all numbers (1*2*3*4...).','O(n log n) is used by Quicksort and Merge Sort, not the Travelling Salesman.'],choices:[],why:[],altAnswers:[]},
  {id:17,type:'mc',difficulty:'medium',slideRef:'Section 3.3 — Big-O Determination Rules',question:'What does O(n^2 + n) simplify to in Big-O notation?',correctAnswer:'O(n^2)',origChoices:['O(n)','O(2n)','O(n^3)','O(n^2)'],origWhy:['O(n) drops the dominant term; we drop lower-order terms, not the highest-order term.','O(2n) would mean combining equal-order terms; n^2 and n are not the same order.','O(n^3) would be a higher complexity — dropping lower-order terms never increases the class.','O(n^2) is correct. The reviewer states: "Dropping lower-order terms — O(n^2 + n) simplifies to O(n^2)."'],choices:[],why:[],altAnswers:[]},
  {id:18,type:'mc',difficulty:'easy',slideRef:'Section 1.3 — Python Lists vs. Tuples vs. Dictionaries',question:'Which Python data structure maps unique keys to values and provides O(1) average-case lookup?',correctAnswer:'Dictionary',origChoices:['List','Tuple','Dictionary','Set'],origWhy:['A List stores ordered elements accessed by index — it does not use key-value mapping.','A Tuple is an immutable ordered sequence — it does not support key-value mapping.','Dictionary is correct. The reviewer states: "Dictionary (dict) — Maps unique keys to values. Provides O(1) average-case lookup. Implemented as a hash table."','A Set is not covered in the reviewer\'s comparison table and does not use key-value mapping.'],choices:[],why:[],altAnswers:[]},
  {id:19,type:'mc',difficulty:'easy',slideRef:'Section 4.1 — Python List Methods — Time Complexity',question:'What is the time complexity of lst.remove(x) — removing the first occurrence of value x in a Python list?',correctAnswer:'O(n)',origChoices:['O(1)','O(log n)','O(n log n)','O(n)'],origWhy:['O(1) is constant time — achieved only by lst.pop() (removing the last element), not by value-based search and removal.','O(log n) is logarithmic — used in Binary Search on sorted data, not value removal.','O(n log n) is used by sorting operations (lst.sort()), not removal of a single element.','O(n) is correct. lst.remove(x) must search through the list to find x, which is a linear scan.'],choices:[],why:[],altAnswers:[]},
  {id:20,type:'mc',difficulty:'medium',slideRef:'Section 4.1 — Python List Methods — Time Complexity',question:'What is the time complexity of lst[i:j] (list slicing), where k = j - i is the length of the slice?',correctAnswer:'O(k)',origChoices:['O(1)','O(n)','O(k)','O(n log n)'],origWhy:['O(1) would mean slicing takes the same time regardless of slice length — this is not the case, as each element must be copied.','O(n) would mean the full list length is always traversed, but only the slice length k is relevant.','O(k) is correct. The reviewer lists lst[i:j] as O(k) where k = j - i, meaning cost grows with the slice length.','O(n log n) is the cost of sorting — far more complex than slicing.'],choices:[],why:[],altAnswers:[]},
  {id:21,type:'tf',difficulty:'easy',slideRef:'Section 1.3 — Python Lists vs. Tuples vs. Dictionaries',question:'A Python List is mutable — its elements can be changed after creation.',correctAnswer:'True',origChoices:['True','False'],origWhy:['True is correct. The reviewer\'s table shows List as "Mutable? Yes." A list supports adding, removing, and modifying elements.','False is incorrect. Unlike a Tuple (which is immutable), a List is explicitly described as mutable.'],choices:[],why:[],altAnswers:[]},
  {id:22,type:'tf',difficulty:'medium',slideRef:'Section 3.1 — Big-O Overview',question:'Big-O notation describes the lower bound of an algorithm\'s growth rate.',correctAnswer:'False',origChoices:['True','False'],origWhy:['True is incorrect. A lower bound is described by Big-Omega (Ω) notation, not Big-O.','False is correct. The reviewer explicitly states: "Big-O describes an upper bound." It captures the worst-case asymptotic growth rate, not the lower bound.'],choices:[],why:[],altAnswers:[]},
  {id:23,type:'tf',difficulty:'easy',slideRef:'Section 1.4 — Key Array/List Operations and Big-O',question:'The Python operation arr.append(x) has O(1) amortized time complexity.',correctAnswer:'True',origChoices:['True','False'],origWhy:['True is correct. The reviewer lists arr.append(x) as "O(1) amort." meaning amortized constant time. Occasional internal resizing is O(n), but when averaged over many appends, the cost per append is O(1).','False is incorrect. Although occasional resizing is O(n), the amortized (average over many operations) cost is O(1) as stated in the reviewer.'],choices:[],why:[],altAnswers:[]},
  {id:24,type:'tf',difficulty:'easy',slideRef:'Section 1.3 — Python Lists vs. Tuples vs. Dictionaries',question:'Python Tuples are ordered.',correctAnswer:'True',origChoices:['True','False'],origWhy:['True is correct. The reviewer\'s table shows Tuple as "Ordered? Yes." Elements in a tuple maintain insertion order.','False is incorrect. The reviewer explicitly shows Tuples as ordered in its comparison table.'],choices:[],why:[],altAnswers:[]},
  {id:25,type:'tf',difficulty:'medium',slideRef:'Section 3.1 — Big-O Overview / Section 2.4 — Analysis of Algorithms',question:'Donald Knuth created Big-O notation.',correctAnswer:'False',origChoices:['True','False'],origWhy:['True is incorrect. Donald Knuth pioneered the formal study of algorithm analysis, but he did not create Big-O notation.','False is correct. The reviewer clearly distinguishes: Big-O was created by Paul Bachmann and Edmund Landau (Section 3.1), while Donald Knuth is credited for pioneering algorithm analysis (Section 2.4).'],choices:[],why:[],altAnswers:[]},
  {id:26,type:'tf',difficulty:'easy',slideRef:'Section 3.2 — Big-O Classes / Section 4.2 — Key Vocabulary',question:'Linear Search has O(n) time complexity and works on unsorted data.',correctAnswer:'True',origChoices:['True','False'],origWhy:['True is correct. The reviewer states in Section 3.2: "O(n) [Linear] — Ex: Finding an item in an unsorted list." Section 4.2 confirms: "Linear Search — O(n) scan; works on unsorted data."','False is incorrect. Both the Big-O classes table and the Key Vocabulary section confirm O(n) for Linear Search on unsorted data.'],choices:[],why:[],altAnswers:[]},
  {id:27,type:'tf',difficulty:'easy',slideRef:'Section 3.3 — Big-O Determination Rules',question:'In Big-O notation, O(2n) simplifies to O(n) by dropping the constant multiplier.',correctAnswer:'True',origChoices:['True','False'],origWhy:['True is correct. The reviewer states: "Dropping constants — O(2n) simplifies to O(n); only the dominant growth term is kept."','False is incorrect. Dropping constants is a fundamental rule of Big-O simplification explicitly stated in the reviewer.'],choices:[],why:[],altAnswers:[]},
  {id:28,type:'tf',difficulty:'easy',slideRef:'Section 1.2 — 1D vs. 2D Arrays',question:'A 2D array element is accessed using a single index (e.g., arr[i]).',correctAnswer:'False',origChoices:['True','False'],origWhy:['True is incorrect. A single index accesses elements in a 1D array (arr[i]). A 2D array requires two indices.','False is correct. The reviewer states: "Individual elements accessed by specifying two indices: arr[i][j], where i = row, j = column." The example grid[1][2] → 6 confirms this.'],choices:[],why:[],altAnswers:[]},
  {id:29,type:'tf',difficulty:'easy',slideRef:'Section 2.5 — Types of Analysis',question:'Best-case analysis measures the minimum number of steps required for an optimal input of size n.',correctAnswer:'True',origChoices:['True','False'],origWhy:['True is correct. The reviewer\'s table defines Best-case as "Minimum number of steps for optimal input of size n."','False is incorrect. The reviewer explicitly distinguishes Best-case (minimum steps) from Worst-case (maximum steps) and Average-case.'],choices:[],why:[],altAnswers:[]},
  {id:30,type:'tf',difficulty:'easy',slideRef:'Section 1.3 — Python Lists vs. Tuples vs. Dictionaries',question:'Python Dictionaries have been ordered (maintain insertion order) since version 3.7.',correctAnswer:'True',origChoices:['True','False'],origWhy:['True is correct. The reviewer\'s table shows Dictionary as "Ordered? Yes (3.7+)", meaning Dictionaries are ordered starting from Python 3.7.','False is incorrect. The reviewer explicitly notes "(3.7+)" in the Ordered column for Dictionaries.'],choices:[],why:[],altAnswers:[]},
  {id:31,type:'enum',difficulty:'medium',slideRef:'Section 2.2 — Algorithm Formulation Steps',question:'List all 5 steps of Algorithm Formulation in the correct order as presented in the reviewer.',correctAnswer:['Understand the problem','Design the algorithm','Analyze the algorithm','Refine the algorithm','Verification'],origChoices:[],origWhy:['The reviewer lists five numbered steps: 1. Understand the problem, 2. Design the algorithm, 3. Analyze the algorithm, 4. Refine the algorithm, 5. Verification.'],choices:[],why:[],altAnswers:[['understand','design','analyze','refine','verification'],['understand the problem','design the algorithm','analyze the algorithm','refine the algorithm','verify']]},
  {id:32,type:'enum',difficulty:'easy',slideRef:'Section 2.5 — Types of Analysis',question:'List all 4 types of algorithm analysis as presented in the reviewer\'s table.',correctAnswer:['Worst-case','Best-case','Average-case','Amortized'],origChoices:[],origWhy:['The reviewer\'s Types of Analysis table lists four entries: Worst-case, Best-case, Average-case, and Amortized.'],choices:[],why:[],altAnswers:[]},
  {id:33,type:'enum',difficulty:'easy',slideRef:'Section 1.2 — 1D vs. 2D Arrays',question:'List the 4 use cases for 2D arrays as explicitly mentioned in the reviewer.',correctAnswer:['Matrices','Game boards','Image pixel data','Spreadsheet-like structures'],origChoices:[],origWhy:['The reviewer states: "Use cases for 2D arrays — Matrices, game boards, image pixel data, spreadsheet-like structures."'],choices:[],why:[],altAnswers:[['matrices','game boards','image pixel data','spreadsheet-like structures'],['matrix','game board','image pixel data','spreadsheet']]},
  {id:34,type:'id',difficulty:'easy',slideRef:'Section 1.1 — What is an Array?',question:'Described in the reviewer as "the most basic data structure for storing and accessing a collection of data" that stores a fixed-size sequential collection of elements of the same type. What is it?',correctAnswer:'Array',origChoices:[],origWhy:[],choices:[],why:[],altAnswers:['array','arrays']},
  {id:35,type:'id',difficulty:'medium',slideRef:'Section 2.5 — Types of Analysis',question:'Which type of algorithm analysis computes the average cost over a sequence of operations, spread over time? (e.g., list.append is this type because occasional resizing is O(n) but the per-operation average is O(1))',correctAnswer:'Amortized',origChoices:[],origWhy:[],choices:[],why:[],altAnswers:['amortized','amortized analysis']},
  {id:36,type:'id',difficulty:'easy',slideRef:'Section 2.4 — Analysis of Algorithms',question:'According to the reviewer, who is the pioneer in the formal study of algorithm analysis?',correctAnswer:'Donald Knuth',origChoices:[],origWhy:[],choices:[],why:[],altAnswers:['donald knuth','knuth']},
  {id:37,type:'id',difficulty:'medium',slideRef:'Section 4.1 — Python List Methods — Time Complexity',question:'The reviewer identifies this in-place sorting algorithm as the one used by Python\'s lst.sort() method, with a time complexity of O(n log n). What is it called?',correctAnswer:'Timsort',origChoices:[],origWhy:[],choices:[],why:[],altAnswers:['timsort','tim sort']},
  {id:38,type:'id',difficulty:'easy',slideRef:'Section 1.3 — Python Lists vs. Tuples vs. Dictionaries',question:'Which Python data structure is described as immutable and is "used for fixed data that should not change"? It is slightly more memory-efficient than a list.',correctAnswer:'Tuple',origChoices:[],origWhy:[],choices:[],why:[],altAnswers:['tuple','tuples']},
  {id:39,type:'id',difficulty:'easy',slideRef:'Section 2.3 — Computational Complexity',question:'The reviewer defines this as "expressed as the number of steps or operations the algorithm executes as a function of input size n." What type of complexity is this?',correctAnswer:'Time Complexity',origChoices:[],origWhy:[],choices:[],why:[],altAnswers:['time complexity','time']},
  {id:40,type:'id',difficulty:'easy',slideRef:'Section 2.3 — Computational Complexity',question:'The reviewer defines this as "expressed as the amount of memory (storage) required to solve the problem as a function of n." What type of complexity is this?',correctAnswer:'Space Complexity',origChoices:[],origWhy:[],choices:[],why:[],altAnswers:['space complexity','space']},
  {id:41,type:'id',difficulty:'easy',slideRef:'Section 3.2 — Big-O Classes (from fastest to slowest)',question:'Quicksort and Merge Sort are classic examples of which Big-O complexity class?',correctAnswer:'O(n log n)',origChoices:[],origWhy:[],choices:[],why:[],altAnswers:['o(n log n)','n log n','o(nlogn)','nlogn']},
  {id:42,type:'id',difficulty:'easy',slideRef:'Section 1.1 — What is an Array?',question:'In the reviewer, each array element is accessed via this zero-based mechanism (e.g., arr[0]), and access time is O(1). What is this access mechanism called?',correctAnswer:'Index',origChoices:[],origWhy:[],choices:[],why:[],altAnswers:['index','indexing','zero-based index']},
  {id:43,type:'id',difficulty:'medium',slideRef:'Section 4.2 — Key Vocabulary',question:'The reviewer\'s cheat sheet defines this as the "study of algorithm behavior as n → infinity; ignores constants and lower-order terms." What is this type of analysis called?',correctAnswer:'Asymptotic analysis',origChoices:[],origWhy:[],choices:[],why:[],altAnswers:['asymptotic analysis','asymptotic','asymptotic complexity']},
  {id:44,type:'acronym',difficulty:'easy',slideRef:'Reviewer Header — Kim Cedrick C. Villar | BSIT & IT-252 | DASTRUC',question:'What does DASTRUC stand for? (as used in the reviewer\'s header)',correctAnswer:'Data Structures',origChoices:[],origWhy:[],choices:[],why:[],altAnswers:['data structures','data structure']},
  {id:45,type:'acronym',difficulty:'easy',slideRef:'Reviewer Header — Kim Cedrick C. Villar | BSIT & IT-252 | DASTRUC',question:'What does BSIT stand for? (as shown in the reviewer\'s header)',correctAnswer:'Bachelor of Science in Information Technology',origChoices:[],origWhy:[],choices:[],why:[],altAnswers:['bachelor of science in information technology','bs information technology','bachelor of science information technology']},
  {id:46,type:'acronym',difficulty:'easy',slideRef:'Section 3.1 — Big-O Overview',question:'The reviewer states Big-O is "also called" by this two-word hyphenated name, after its two creators. What is that name?',correctAnswer:'Bachmann-Landau notation',origChoices:[],origWhy:[],choices:[],why:[],altAnswers:['bachmann-landau notation','bachmann landau notation','bachmann\u2013landau notation','bachmann-landau']},
  {id:47,type:'acronym',difficulty:'easy',slideRef:'Section 3.1 — Big-O Overview',question:'What does CS stand for as used in the reviewer? (Section 3.1 mentions "Purpose in CS")',correctAnswer:'Computer Science',origChoices:[],origWhy:[],choices:[],why:[],altAnswers:['computer science']},
  {id:48,type:'acronym',difficulty:'easy',slideRef:'Reviewer Header — Kim Cedrick C. Villar | BSIT & IT-252 | DASTRUC',question:'What does IT stand for, as seen in "BSIT" and "IT-252" throughout the reviewer?',correctAnswer:'Information Technology',origChoices:[],origWhy:[],choices:[],why:[],altAnswers:['information technology']}
];

const examState={answers:{},flagged:{},currentStreak:0,longestStreak:0,submitted:false,startTime:null,remainingTime:null,questions:[]};
let timerInterval=null,currentFilter='all';
const TYPE_ORDER=['mc','tf','enum','id','acronym'];

function shuffle(arr){const a=[...arr];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
function normalize(str){if(str==null)return'';return String(str).toLowerCase().trim().replace(/\s+/g,' ').replace(/[.,!?;:'"()\-\u2013\u2014]/g,'').trim();}
function formatTime(secs){const m=Math.floor(secs/60).toString().padStart(2,'0');const s=(secs%60).toString().padStart(2,'0');return`${m}:${s}`;}
function typeBadgeClass(t){return{mc:'badge-mc',tf:'badge-tf',enum:'badge-enum',id:'badge-id',acronym:'badge-acronym'}[t]||'';}
function typeLabelFull(t){return{mc:'Multiple Choice',tf:'True or False',enum:'Enumeration',id:'Identification',acronym:'Acronym Meaning'}[t]||t;}
function diffClass(d){return{easy:'diff-easy',medium:'diff-medium',hard:'diff-hard'}[d]||'diff-medium';}

function checkAnswer(q,userAnswer){
  if(q.type==='mc'||q.type==='tf')return normalize(userAnswer)===normalize(q.correctAnswer);
  if(q.type==='id'||q.type==='acronym'){const norm=normalize(userAnswer);if(!norm)return false;const alts=(q.altAnswers||[]).map(normalize);return norm===normalize(q.correctAnswer)||alts.includes(norm);}
  if(q.type==='enum'){if(!userAnswer||!Array.isArray(userAnswer))return false;const{matched}=scoreEnum(q,userAnswer);return matched===q.correctAnswer.length;}
  return false;
}

function scoreEnum(q,userAnswers){
  const expected=q.correctAnswer.map(normalize);const altSets=q.altAnswers||[];
  const userNorm=(userAnswers||[]).map(normalize).filter(Boolean);const matched=[];const usedExpected=new Set();
  for(const ua of userNorm){for(let i=0;i<expected.length;i++){if(usedExpected.has(i))continue;if(ua===expected[i]){usedExpected.add(i);matched.push(i);break;}let foundAlt=false;for(const altGroup of altSets){if(altGroup[i]&&normalize(altGroup[i])===ua){usedExpected.add(i);matched.push(i);foundAlt=true;break;}}if(foundAlt)break;}}
  return{matched:matched.length,total:expected.length,matchedIndices:matched};
}

function initExam(){
  if(timerInterval){clearInterval(timerInterval);timerInterval=null;}
  Object.assign(examState,{answers:{},flagged:{},currentStreak:0,longestStreak:0,submitted:false,startTime:Date.now(),remainingTime:20*60});
  const groups={};TYPE_ORDER.forEach(t=>{groups[t]=[];});questionBank.forEach(q=>{if(groups[q.type])groups[q.type].push(q);});
  examState.questions=[];
  TYPE_ORDER.forEach(type=>{shuffle(groups[type]).forEach(q=>{const cloned={...q,origChoices:[...q.origChoices],origWhy:[...q.origWhy],altAnswers:[...(q.altAnswers||[])],correctAnswer:Array.isArray(q.correctAnswer)?[...q.correctAnswer]:q.correctAnswer};if(q.type==='mc'){const idx=q.origChoices.map((_,i)=>i);const si=shuffle(idx);cloned.shuffledChoices=si.map(i=>q.origChoices[i]);const ci=q.origChoices.indexOf(q.correctAnswer);cloned.correctShuffledIndex=si.indexOf(ci);}else if(q.type==='tf'){cloned.shuffledChoices=['True','False'];cloned.correctShuffledIndex=q.correctAnswer==='True'?0:1;}examState.questions.push(cloned);});});
  currentFilter='all';document.querySelectorAll('.filter-btn').forEach(b=>b.classList.remove('active'));const ab=document.querySelector('.filter-btn[data-filter="all"]');if(ab)ab.classList.add('active');
  const sb=document.getElementById('summary-box');if(sb)sb.remove();
  updateTimerDisplay();startTimer();renderQuestions();renderNavigator();updateProgress();
  const tel=document.getElementById('timer-display');if(tel)tel.classList.remove('warn','danger');
}

function renderQuestions(){
  const section=document.getElementById('question-section');const existingSummary=document.getElementById('summary-box');
  section.innerHTML='';if(existingSummary)section.appendChild(existingSummary);
  const submitArea=buildSubmitArea();const questionsToShow=filterQuestions();let lastType=null,groupDiv=null;
  questionsToShow.forEach(q=>{const realIndex=examState.questions.indexOf(q);if(q.type!==lastType){const gw=document.createElement('div');gw.style.marginBottom='28px';const h=document.createElement('div');h.className='group-header';h.textContent=typeLabelFull(q.type);gw.appendChild(h);groupDiv=gw;section.appendChild(gw);lastType=q.type;}groupDiv.appendChild(buildQuestionCard(q,realIndex+1));});
  section.appendChild(submitArea);
}

function buildQuestionCard(q,displayNum){
  const card=document.createElement('div');card.className='question-card'+(examState.flagged[q.id]?' is-flagged':'');card.id=`card-${q.id}`;card.setAttribute('data-qid',q.id);
  const meta=document.createElement('div');meta.className='question-meta';
  meta.innerHTML=`<span class="q-number">${displayNum}</span><span class="q-type-badge ${typeBadgeClass(q.type)}">${typeLabelFull(q.type)}</span><span class="q-difficulty ${diffClass(q.difficulty)}">${q.difficulty}</span><span class="q-slide-ref" title="Source reference">📑 ${q.slideRef}</span><button class="flag-btn${examState.flagged[q.id]?' flagged':''}" onclick="toggleFlag(${q.id})" aria-label="${examState.flagged[q.id]?'Unflag':'Flag'} question ${displayNum}" aria-pressed="${!!examState.flagged[q.id]}">${examState.flagged[q.id]?'🚩 Flagged':'⚑ Flag'}</button>`;
  card.appendChild(meta);
  const qText=document.createElement('div');qText.className='question-text';qText.textContent=q.question;card.appendChild(qText);
  const inputArea=document.createElement('div');
  if(q.type==='mc'||q.type==='tf'){inputArea.className='choices-list';const choices=q.shuffledChoices||['True','False'];choices.forEach((choice,ci)=>{const btn=document.createElement('button');btn.className='choice-btn'+(examState.answers[q.id]===choice?' selected':'');btn.disabled=examState.submitted;btn.setAttribute('aria-label',`Choice ${String.fromCharCode(65+ci)}: ${choice}`);btn.innerHTML=`<span class="choice-letter">${String.fromCharCode(65+ci)}</span><span>${choice}</span>`;if(!examState.submitted)btn.onclick=()=>handleAnswer(q.id,choice);inputArea.appendChild(btn);});}
  else if(q.type==='enum'){inputArea.className='enum-input-wrap';q.correctAnswer.forEach((_,i)=>{const wrap=document.createElement('div');wrap.innerHTML=`<div class="enum-item-label">Answer ${i+1}</div>`;const inp=document.createElement('input');inp.type='text';inp.className='answer-input';inp.placeholder=`Enter answer ${i+1}...`;inp.setAttribute('aria-label',`Enumeration answer ${i+1} for question ${q.id}`);inp.disabled=examState.submitted;const saved=examState.answers[q.id];if(saved&&saved[i])inp.value=saved[i];inp.oninput=()=>{const vals=[];inputArea.querySelectorAll('.answer-input').forEach(el=>vals.push(el.value));handleAnswer(q.id,vals);};wrap.appendChild(inp);inputArea.appendChild(wrap);});}
  else{inputArea.className='text-input-wrap';const inp=document.createElement('input');inp.type='text';inp.className='answer-input';inp.placeholder=q.type==='acronym'?'Enter the full meaning...':'Type your answer...';inp.setAttribute('aria-label',`Answer for question ${q.id}`);inp.disabled=examState.submitted;if(examState.answers[q.id])inp.value=examState.answers[q.id];inp.oninput=()=>handleAnswer(q.id,inp.value);inputArea.appendChild(inp);}
  card.appendChild(inputArea);
  if(examState.submitted)applyReviewState(card,q);
  return card;
}

function applyReviewState(card,q){
  const isCorrect=checkAnswer(q,examState.answers[q.id]);
  const hasAnswer=examState.answers[q.id]!==undefined&&examState.answers[q.id]!==''&&!(Array.isArray(examState.answers[q.id])&&examState.answers[q.id].every(v=>!v));
  card.classList.remove('is-flagged');card.classList.add(isCorrect?'result-correct':'result-incorrect');if(examState.flagged[q.id])card.classList.add('is-flagged');
  if(q.type==='mc'||q.type==='tf'){const choices=q.shuffledChoices||['True','False'];card.querySelectorAll('.choice-btn').forEach((btn,ci)=>{btn.classList.remove('selected');const isCor=choices[ci]===q.correctAnswer;const isUser=examState.answers[q.id]===choices[ci];if(isCor)btn.classList.add('review-correct');else if(isUser&&!isCor)btn.classList.add('review-wrong-selected');});}
  const ind=document.createElement('div');ind.className='result-indicator '+(isCorrect?'result-correct-ind':hasAnswer?'result-incorrect-ind':'result-skipped-ind');ind.innerHTML=isCorrect?'✓ Correct':hasAnswer?'✗ Incorrect':'— Skipped';card.appendChild(ind);
  if(q.type==='id'||q.type==='acronym'){const box=document.createElement('div');box.className='correct-answer-box';box.innerHTML=`<strong>Accepted answer:</strong> ${q.correctAnswer}${q.altAnswers&&q.altAnswers.length?`<br><span style="font-size:12px;color:var(--neutral-500)">Also accepted: ${q.altAnswers.join(', ')}</span>`:''}`;card.appendChild(box);if(hasAnswer&&!isCorrect){const ua=document.createElement('div');ua.className='id-review-answer id-user-answer';ua.innerHTML=`<strong>Your answer:</strong> ${examState.answers[q.id]||'—'}`;card.appendChild(ua);}}
  if(q.type==='enum'){const userAnswers=examState.answers[q.id]||[];const{matchedIndices}=scoreEnum(q,userAnswers);const matchedSet=new Set(matchedIndices);const er=document.createElement('div');er.className='enum-review';q.correctAnswer.forEach((exp,i)=>{const row=document.createElement('div');row.className='enum-match '+(matchedSet.has(i)?'matched':'missing');row.textContent=(matchedSet.has(i)?'✓ ':'✗ Missing: ')+exp;er.appendChild(row);});const pt=document.createElement('div');pt.className='enum-partial-score';pt.textContent=`Score: ${matchedIndices.length} / ${q.correctAnswer.length} matched`;er.appendChild(pt);card.appendChild(er);}
  if(q.type==='mc'||q.type==='tf'){const eb=document.createElement('div');eb.className='explanation-box';const t=document.createElement('div');t.className='exp-title';t.textContent='Explanation (based on original answer order)';eb.appendChild(t);q.origChoices.forEach((ch,oi)=>{const isCor=ch===q.correctAnswer;const row=document.createElement('div');row.className='exp-row'+(isCor?' exp-correct-row':'');row.innerHTML=`<span class="exp-letter">${String.fromCharCode(65+oi)}.</span><span><strong>${ch}</strong> — ${q.origWhy[oi]||''}</span>`;eb.appendChild(row);});card.appendChild(eb);}
  if(q.type==='tf'){const eb=card.querySelector('.explanation-box');if(eb){const note=document.createElement('div');note.style.cssText='font-size:11px;color:var(--neutral-400);margin-top:6px;font-style:italic;';note.textContent='Note: Explanation letters above reflect the original True/False order; choices shown during the exam may appear in a different order.';eb.appendChild(note);}}
  if((q.type==='id'||q.type==='acronym')&&q.origWhy&&q.origWhy.length){const eb=document.createElement('div');eb.className='explanation-box';eb.innerHTML=`<div class="exp-title">Explanation</div><div>${q.origWhy[0]}</div>`;card.appendChild(eb);}
}

function buildSubmitArea(){
  const div=document.createElement('div');div.id='submit-area';if(examState.submitted){div.style.display='none';return div;}
  div.innerHTML=`<button id="submit-btn" onclick="submitExam()" aria-label="Submit exam">Submit Exam</button><div class="submit-note">Once submitted, answers cannot be changed.</div>`;
  return div;
}

function handleAnswer(qId,value){
  if(examState.submitted)return;examState.answers[qId]=value;updateProgress();updateNavigatorBtn(qId);
  const card=document.getElementById(`card-${qId}`);if(!card)return;const q=examState.questions.find(x=>x.id===qId);if(!q)return;
  if(q.type==='mc'||q.type==='tf'){card.querySelectorAll('.choice-btn').forEach(btn=>{const label=btn.querySelector('span:last-child');if(label&&label.textContent===value)btn.classList.add('selected');else btn.classList.remove('selected');});}
}

function submitExam(){
  if(examState.submitted)return;examState.submitted=true;if(timerInterval){clearInterval(timerInterval);timerInterval=null;}
  let streak=0;examState.longestStreak=0;examState.questions.forEach(q=>{if(checkAnswer(q,examState.answers[q.id])){streak++;if(streak>examState.longestStreak)examState.longestStreak=streak;}else{streak=0;}});
  const sa=document.getElementById('submit-area');if(sa)sa.style.display='none';
  document.querySelectorAll('.filter-btn').forEach(b=>b.classList.remove('active'));const ab=document.querySelector('.filter-btn[data-filter="all"]');if(ab)ab.classList.add('active');currentFilter='all';
  renderResults();renderNavigator();updateProgress();
}

function renderResults(){
  const section=document.getElementById('question-section');const existingSummary=document.getElementById('summary-box');if(existingSummary)existingSummary.remove();
  let totalScore=0,enumScore=0,enumTotal=0;const typeTotals={},typeCorrects={};TYPE_ORDER.forEach(t=>{typeTotals[t]=0;typeCorrects[t]=0;});
  examState.questions.forEach(q=>{typeTotals[q.type]=(typeTotals[q.type]||0)+(q.type==='enum'?q.correctAnswer.length:1);if(q.type==='enum'){enumTotal+=q.correctAnswer.length;const{matched}=scoreEnum(q,examState.answers[q.id]||[]);enumScore+=matched;typeCorrects['enum']=(typeCorrects['enum']||0)+matched;}else{if(checkAnswer(q,examState.answers[q.id])){totalScore++;typeCorrects[q.type]=(typeCorrects[q.type]||0)+1;}}});
  const grandTotal=(examState.questions.length-examState.questions.filter(q=>q.type==='enum').length)+enumTotal;
  const grandScore=totalScore+enumScore;const pct=Math.round((grandScore/grandTotal)*100);const pass=pct>=75;
  const answered=Object.keys(examState.answers).filter(id=>{const q=examState.questions.find(x=>x.id==id);if(!q)return false;const ans=examState.answers[id];if(Array.isArray(ans))return ans.some(v=>v&&v.trim());return ans!==undefined&&ans!=='';}).length;
  const skipped=examState.questions.length-answered;
  const summaryBox=document.createElement('div');summaryBox.id='summary-box';
  summaryBox.innerHTML=`<div style="display:flex;align-items:baseline;flex-wrap:wrap;gap:8px;"><div><span class="summary-score">${grandScore}</span><span class="summary-pct">/ ${grandTotal}</span></div><span class="summary-badge ${pass?'badge-pass':'badge-fail'}">${pass?'✓ PASSED':'✗ FAILED'}</span></div><div class="summary-stats"><div class="stat-item"><span class="stat-label">Percentage</span><span class="stat-val">${pct}%</span></div><div class="stat-item"><span class="stat-label">Answered</span><span class="stat-val">${answered}</span></div><div class="stat-item"><span class="stat-label">Skipped</span><span class="stat-val">${skipped}</span></div><div class="stat-item"><span class="stat-label">Longest Streak</span><span class="stat-val">${examState.longestStreak}</span></div></div><div class="summary-section-breakdown"><div style="font-size:13px;font-weight:700;margin-bottom:6px;color:var(--neutral-600);">Section Breakdown</div>${TYPE_ORDER.map(t=>{const tc=typeCorrects[t]||0;const tt=typeTotals[t]||0;const tp=tt>0?Math.round((tc/tt)*100):0;return`<div class="breakdown-row"><span>${typeLabelFull(t)}</span><span style="font-family:var(--mono);font-weight:600;">${tc} / ${tt} (${tp}%)</span></div>`;}).join('')}</div><button class="retake-btn" onclick="retakeExam()" aria-label="Retake the exam">Retake Exam</button>`;
  section.insertBefore(summaryBox,section.firstChild);
  examState.questions.forEach(q=>{const e=document.getElementById(`card-${q.id}`);if(e)e.remove();});
  let lastType=null,groupDiv=null;examState.questions.forEach((q,idx)=>{if(q.type!==lastType){const gw=document.createElement('div');gw.style.marginBottom='28px';const h=document.createElement('div');h.className='group-header';h.textContent=typeLabelFull(q.type);gw.appendChild(h);groupDiv=gw;section.appendChild(gw);lastType=q.type;}groupDiv.appendChild(buildQuestionCard(q,idx+1));});
}

function renderNavigator(){
  const grid=document.getElementById('navigator-grid');if(!grid)return;grid.innerHTML='';
  examState.questions.forEach((q,idx)=>{const btn=document.createElement('button');btn.textContent=idx+1;btn.setAttribute('aria-label',`Go to question ${idx+1}`);updateNavBtnClasses(btn,q);btn.onclick=()=>scrollToCard(q.id);grid.appendChild(btn);});
}

function updateNavBtnClasses(btn,q){
  btn.className='nav-btn';
  const hasAnswer=examState.answers[q.id]!==undefined&&examState.answers[q.id]!==''&&!(Array.isArray(examState.answers[q.id])&&examState.answers[q.id].every(v=>!v));
  if(examState.submitted){const correct=checkAnswer(q,examState.answers[q.id]);btn.classList.add(correct?(examState.flagged[q.id]?'nav-flagged-correct':'nav-correct'):(examState.flagged[q.id]?'nav-flagged-incorrect':'nav-incorrect'));}
  else{if(hasAnswer)btn.classList.add('answered');if(examState.flagged[q.id])btn.classList.add('flagged');}
}

function updateNavigatorBtn(qId){const q=examState.questions.find(x=>x.id===qId);if(!q)return;const idx=examState.questions.indexOf(q);const btns=document.querySelectorAll('#navigator-grid .nav-btn');if(btns[idx])updateNavBtnClasses(btns[idx],q);}
function scrollToCard(qId){const card=document.getElementById(`card-${qId}`);if(card)card.scrollIntoView({behavior:'smooth',block:'center'});}

function toggleFlag(qId){
  examState.flagged[qId]=!examState.flagged[qId];const card=document.getElementById(`card-${qId}`);
  if(card){if(examState.flagged[qId])card.classList.add('is-flagged');else card.classList.remove('is-flagged');const fb=card.querySelector('.flag-btn');if(fb){fb.className='flag-btn'+(examState.flagged[qId]?' flagged':'');fb.setAttribute('aria-pressed',!!examState.flagged[qId]);fb.innerHTML=examState.flagged[qId]?'🚩 Flagged':'⚑ Flag';}}
  const q=examState.questions.find(x=>x.id===qId);if(q)updateNavigatorBtn(qId);
}

function resetFlags(){
  examState.flagged={};document.querySelectorAll('.question-card.is-flagged').forEach(c=>c.classList.remove('is-flagged'));
  document.querySelectorAll('.flag-btn.flagged').forEach(b=>{b.className='flag-btn';b.setAttribute('aria-pressed','false');b.innerHTML='⚑ Flag';});renderNavigator();
}

function filterQuestions(){
  if(!examState.submitted&&currentFilter!=='all'&&currentFilter!=='flagged')return examState.questions;
  if(currentFilter==='all')return examState.questions;
  if(currentFilter==='flagged')return examState.questions.filter(q=>examState.flagged[q.id]);
  if(currentFilter==='correct')return examState.questions.filter(q=>checkAnswer(q,examState.answers[q.id]));
  if(currentFilter==='incorrect')return examState.questions.filter(q=>!checkAnswer(q,examState.answers[q.id]));
  return examState.questions;
}

function setFilter(f){
  currentFilter=f;document.querySelectorAll('.filter-btn').forEach(b=>b.classList.toggle('active',b.dataset.filter===f));
  if(examState.submitted)renderResults();else renderQuestions();
}

function updateProgress(){
  const answered=examState.questions.filter(q=>{const ans=examState.answers[q.id];if(ans===undefined||ans==='')return false;if(Array.isArray(ans))return ans.some(v=>v&&v.trim());return true;}).length;
  const total=examState.questions.length;const pct=total>0?Math.round((answered/total)*100):0;
  const bar=document.getElementById('progress-bar');const txt=document.getElementById('progress-text');const pctEl=document.getElementById('progress-pct');
  if(bar)bar.style.width=pct+'%';if(txt)txt.textContent=`${answered} / ${total} answered`;if(pctEl)pctEl.textContent=pct+'%';
}

function startTimer(){
  if(timerInterval){clearInterval(timerInterval);timerInterval=null;}
  timerInterval=setInterval(()=>{if(examState.submitted){clearInterval(timerInterval);timerInterval=null;return;}examState.remainingTime--;updateTimerDisplay();if(examState.remainingTime<=0){clearInterval(timerInterval);timerInterval=null;submitExam();}},1000);
}

function updateTimerDisplay(){
  const el=document.getElementById('timer-display');if(!el)return;el.textContent=formatTime(examState.remainingTime);
  const pct=examState.remainingTime/(20*60);el.classList.remove('warn','danger');
  if(examState.remainingTime<=5*60)el.classList.add('danger');else if(pct<=0.25)el.classList.add('warn');
}

function retakeExam(){document.getElementById('question-section').innerHTML='';initExam();window.scrollTo({top:0,behavior:'smooth'});}

function setDates(){
  const dateStr=new Date().toLocaleDateString(undefined,{year:'numeric',month:'long',day:'numeric'});
  const cd=document.getElementById('credit-date');const fd=document.getElementById('footer-date');
  if(cd)cd.textContent=dateStr;if(fd)fd.textContent=dateStr;
}

setDates();initExam();
